a=set()
for i in range(5):
    print("Enter a value")
    data=int(input())
    a.add(data)
print("Set after adding elements:", a)
a.update([60,70,80])
print("Set after updating with a list:", a)
print("Enter a value to discard")
d1=int(input())
a.discard(d1)
d2=int(input("Enter a value to remove: "))
a.remove(d2)
print("Set after removing elements:", a)